services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api/v1
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      - /app/dist
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
